// samples/widget.svelte
<script lang="ts">
    let count = 0;
    const accent = '#10b981';
</script>

<!--
    Svelte: 일반 style="..." 과 표현식 form 모두 매칭.
    Svelte 고유 `style:property={value}` 은 V0.0.1 미지원 (별도 form).
-->
<div
    style="
        display: flex;
        align-items: center;
        gap: 12px;
        padding: 10px 16px;
        background: #ecfdf5;
        border: 1px solid #a7f3d0;
        border-radius: 10px;
        font-family: system-ui, sans-serif;
        font-size: 14px;
        color: #065f46;
    "
>
    <span style="font-weight: 700; letter-spacing: -0.01em;">Count</span>
    <span style="font-variant-numeric: tabular-nums; min-width: 32px; text-align: right;">
        {count}
    </span>
    <button
        on:click={() => (count += 1)}
        style="
            margin-inline-start: auto;
            padding: 6px 12px;
            background: {accent};
            color: #fff;
            border: 0;
            border-radius: 999px;
            font-weight: 600;
            cursor: pointer;
            transition: transform 120ms ease, opacity 120ms ease;
        "
    >
        +1
    </button>
</div>

<!-- custom property + var() reference -->
<div style="--ring: {accent}; outline: 2px solid var(--ring); outline-offset: 2px; padding: 8px; border-radius: 6px;">
    Ringed
</div>

// samples/Widget.vue
<!--
  Style Pastel sample — Vue inline style 형태.
  - :style="..."  (Vue property binding)
  - style="..."   (정적 inline style)
-->

<template>
    <div
        :style="`display: flex; flex-direction: column; gap: 8px; padding: 12px 16px; min-width: 240px; background: #fdf2f8; border: 1px solid #fbcfe8; border-radius: 10px;`"
    >
        <header
            style="display: flex; align-items: center; justify-content: space-between; gap: 8px; padding-bottom: 8px; border-bottom: 1px solid #fbcfe8;"
        >
            <span
                :style="`font-family: 'Inter', sans-serif; font-size: 13px; font-weight: 600; color: #831843; letter-spacing: 0.04em; text-transform: uppercase;`"
            >
                Notice
            </span>
            <button
                type="button"
                :style="`appearance: none; background: transparent; border: none; cursor: pointer; padding: 4px; color: #831843; font-size: 14px; line-height: 1;`"
            >
                ×
            </button>
        </header>

        <p
            style="font-size: 14px; line-height: 1.5; color: #831843; margin: 0; white-space: pre-wrap; word-break: keep-all;"
        >
            Vue 측 :style 바인딩에서도 카테고리 색이 그대로 보여야 합니다.
        </p>

        <div
            :style="`display: grid; grid-template-columns: 1fr auto; column-gap: 8px; padding: 8px 0; transition: background-color 150ms ease; cursor: pointer; user-select: none;`"
        >
            <span style="font-size: 13px; color: #9d174d;">Action</span>
            <span
                :style="`font-size: 12px; color: #6b7280; transform: translateY(1px); transition: color 120ms ease;`"
            >
                →
            </span>
        </div>
    </div>
</template>

<script setup lang="ts">
// no logic — purely a styling sample
</script>
